

CREATE TABLE if not exists staff
(
    id      INTEGER     NOT NULL,
    name    VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    CONSTRAINT pk_staff PRIMARY KEY (id)
);

CREATE TABLE if not exists staff_role
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_staffrole PRIMARY KEY (id)
);

insert into staff_role (id, name)
values (1, 'TRAINER');
insert into staff_role (id, name)
values (2, 'NUTRITIONIST');
insert into staff_role (id, name)
values (3, 'MASSAGE_THERAPIST');

CREATE TABLE if not exists staff_roles
(
    role_id  INTEGER NOT NULL,
    staff_id INTEGER NOT NULL,
    CONSTRAINT pk_staff_roles PRIMARY KEY (role_id, staff_id)
);

ALTER TABLE staff_roles
    ADD CONSTRAINT fk_starol_on_staff FOREIGN KEY (staff_id) REFERENCES staff (id);

ALTER TABLE staff_roles
    ADD CONSTRAINT fk_starol_on_staff_role FOREIGN KEY (role_id) REFERENCES staff_role (id);

CREATE TABLE if not exists gym
(
    id      BIGINT      NOT NULL,
    address VARCHAR(50) NOT NULL,
    manager VARCHAR(50) NOT NULL,
    CONSTRAINT pk_gym PRIMARY KEY (id)
);

